### ISSUE TITLE
STM32 - ARDUINO 

### ISSUE THREAD

**Issue by madhavanatmel** [Nullkraft/Keypad#13]
HI , I  trying to connect  4x4 matrix keypad with stm32-Blue pill  with arduino .
using the STM32 official core -Duino . keypad is functioning but whenever finger close to the  keypad wiring it's automatically sending the key codes without pressing the keys.
these kind of problems not happening with arduino UNO or NANO  . 
do you think i need connect pull up resistor externally?

**Comment by Nullkraft** [comment]
I searched and the stm32-Blue pill has a default setting for the pins that sets them to tri-state. That would definitely cause the problem that you are seeing. But the Blue pill also has internal pull-up resistors and they are supposed to work with the Arduino code just like any other board.
 
I'm not sure but the only thing I found that might cause a problem is if you are using pins PC13, PC14 or PC15.  If you are using any of those pins as ROW pins you might want to try a different set of pins. Or you could use those pins for your columns instead of rows.
 
If that doesn't help then placing some 22k external resistors should work.

**Comment by madhavanatmel** [comment]
I have used port B for keypad not port c .
i have added external  pull up 22k and now seems to be fine . how ever it's under observation for some days . i have tested with 10 k pull up also .
